apiVersion: v1
kind: ServiceAccount
metadata: 
  name: backend-sa 
  namespace: secureshop
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata: 
  name: read-catalog
  namespace: secureshop
rules:
- apiGroups: [""]
  resources: ["configmaps"] 
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata: 
  name: backend-binding 
  namespace: secureshop
subjects:
- kind: ServiceAccount
  name: backend-sa 
roleRef:
  kind: Role
  name: read-catalog
  apiGroup: rbac.authorization.k8s.io