name: CI Docker Build and Tag

on: 
  push:
    branches:
      -main
    tags:
      - 'v*.*.*'
jobs: 
  build-and-push:
    runs-on: ubuntu-lastest

  steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}