apiVerion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-service
spec:
  type: {{ .Vaules.service.type }}
  selector:
    {{- include "clase21-chart.helpers.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Vaules.service.port }}
      targetPort: 80
      {{- if eq .Vaules.service.type "NodePort" }}
      nodePort: {{ .Vaules.service.nodePort }}
      {{- end}}
    {{- range .Values.extraPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end}}