apiVersion: batch/v1
kind: Job
metadata:
  name: job-factorial
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: worker
        image: busybox
        command: ["sh", "-c", "Calculating the 5 factorial; sleep 3; echo '120'"]
      restartPolicy: Never

         