services:
  api:
    build: .
    image: minimalapilatest
    networks:
      - appnet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  nginx:
    build:
      context: ./nginx
    image: custom-nginx
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - appnet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  appnet:
    driver: bridge
