name: Build & Deploy BlazorApp

on:
  push:
    branches: ["main"]
  
env: 
  DOTNET_VERSION: 8.0.x
  NODE_VERSION: 22.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Descargar el código fuente
      - uses: actions/checkout@v3

      # 2. Configurar el entorno de .NET

      # 3. Paquetes de NuGet

      # 4. Configurar el entorno de Node.js

      # 5. Artifactos de compilación

      # 6. Desplegar a Azure App Service