# Service
apiVersion: v1
kind: Service
metadata: 
  name: fake-db
spec:
  selector: 
    app: fake-db
  ports:
  - port 5432



---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-db
spec: 
  selector:
    matchLabels: {app: fake-db}
  template:
    metadata: {labels: {app: fake-db}}
    spec:
      containers:
      - name: db
        image: alpine
        command: ["sh", "-c", "apk add --no-cache busybox-extras; nc -lk -p 5432"] #
        ports:
        - containerPort: 5432

