apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: demo
  name: read-pods-binding
subjects:
- kind: ServiceAccount
  name: limited-sa 
  namespace: demo
roleRef:
  kind: Role 
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

