apiVersion: v1
kind: Pod
metadata:
  name: sidecar-demo
spec:
  volumes:
  - name: logs
    emptyDir: {}
  containers:
  # --- contenedor principal ---
  - name: app
    image: busybox
    command: ["sh", "-c", "while true; do date >> /var/log/app.log; sleep 2; done"]
    volumeMounts:
    - name: logs
      mountPath: /var/log
  
  # --- Sidecar ---
  - name: log-forwarder
    image: busybox
    command: ["sh", "-c", "tail -n+1 -F /logs/app.log"]
    volumeMounts:
    - name: logs
      mountPath: /var/logs
    