apiVersion: v1
kind: Pod 
metadata:
  name: pod-criminal
  namespace: secureapp
spec:
  containers:
  - name: criminal
    image: alpine:3.20 
    #securityContext:
      #privileged: true
    command: ["sleep", "1h"]
    # securityContext:
    #   allowPrivilegeEscalation: false
    #   capabilities:
    #     drop: ["ALL"]
    #   runAsNonRoot: true
    #   runAsUser: 1000
    #   seccomProfile:
    #     type: RuntimeDefault
