apiVersion: app/v1
kind: Deployment
metadata: 
  name: mysql-db
spec:
  replicas: 1
  selector:
    mathLabels:
      app: mysql-db
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "5f6g7h8j9k01"
        - name: MYSQL_DATABASE
          value: "demo"
        volumeMounts:
        - name: datos-mysql
          mountPath: /var/lib/mysql
      volumenes:
      - name: datos-mysql
        persistentVolumenClaim:
          claimName: demo-pvc
          
